const path = require("path");
const fs = require("fs-extra");

// 不能直接写字符串，避免这个库处理不了自身
const tag = `<!-- ${"generated by magic-list"} -->`;
const nameTag = `<!-- ${"magic-list filename"} -->`;

function parse(absPath) {
  const content = fs.readFileSync(absPath, "utf-8");
  if (!content.match(tag)) {
    throw new Error(`${absPath} is not generated by magic-list.`);
  }

  const fileList = content
    .split(tag)
    .map((str) => {
      const arr = str.split(nameTag);
      if (!arr[1]) {
        return;
      }
      if (!arr[2]) {
        debugger;
      }
      const filename = arr[1].trim().replace(/^`([^]+)`$/, "$1");
      const content = arr[2].trim().replace(/```.+\n([^]+?)```$/, "$1") + "\n";
      return {
        filename,
        content,
      };
      debugger;
    })
    .filter(Boolean);

  const cwd = process.cwd();
  fileList.forEach((f) => {
    const filepath = path.resolve(cwd, f.filename);
    fs.ensureFileSync(filepath);
    fs.writeFileSync(filepath, f.content, "utf-8");
  });
  console.log(absPath);
}

module.exports = {
  parse,
  tag,
  nameTag,
};
